// <auto-generated />
using System;
using Garage_2._0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20191211151017_Seeding-Data")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumnOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfParking")
                        .HasColumnType("datetime2");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volvo",
                            Color = "Green",
                            Model = "Stationwagon",
                            NumnOfWheels = 4,
                            RegNr = "ABC123",
                            TimeOfParking = new DateTime(2019, 12, 11, 16, 10, 16, 811, DateTimeKind.Local).AddTicks(2490),
                            Typ = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scania",
                            Color = "Red",
                            Model = "DoubleDecker",
                            NumnOfWheels = 8,
                            RegNr = "BCD234",
                            TimeOfParking = new DateTime(2019, 12, 11, 16, 10, 16, 814, DateTimeKind.Local).AddTicks(4544),
                            Typ = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Lockheed",
                            Color = "Silver",
                            Model = "DC10",
                            NumnOfWheels = 6,
                            RegNr = "CDE345",
                            TimeOfParking = new DateTime(2019, 12, 11, 16, 10, 16, 814, DateTimeKind.Local).AddTicks(4651),
                            Typ = 3
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Penta",
                            Color = "Brown",
                            Model = "Sailingboat",
                            NumnOfWheels = 0,
                            RegNr = "DEF456",
                            TimeOfParking = new DateTime(2019, 12, 11, 16, 10, 16, 814, DateTimeKind.Local).AddTicks(4661),
                            Typ = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            Color = "Violet",
                            Model = "BladeRunner",
                            NumnOfWheels = 34,
                            RegNr = "ASD345",
                            TimeOfParking = new DateTime(1997, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Typ = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
